spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoservice?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:photoservice}
    password: ${DB_PASSWORD:photoservice123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    com.onecar.photoservice: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: /var/log/photo-service/application.log

app:
  file:
    upload-path: ${UPLOAD_PATH:/data/storage/images}
    temp-path: ${TEMP_PATH:/data/storage/temp}
    cache-path: ${CACHE_PATH:/data/storage/cache}
  security:
    jwt:
      secret: ${JWT_SECRET:prodSecretKey123456789012345678901234567890}
      expiration: 86400000  # 24小时
    max-download-count: ${MAX_DOWNLOAD_COUNT:10000}

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 300
      min-spare: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never