spring:
  datasource:
    url: jdbc:h2:mem:photoservice_test
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: false

logging:
  level:
    com.onecar.photoservice: INFO
    org.springframework: WARN
    org.hibernate: WARN

app:
  file:
    upload-path: ./storage/test/images
    temp-path: ./storage/test/temp
    cache-path: ./storage/test/cache
    max-file-size: 5242880  # 5MB (测试环境较小限制)
  security:
    jwt:
      secret: testSecretKey123456789012345678901234567890
      expiration: 1800000  # 30分钟

server:
  port: 8081